from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Any, Callable

from workflows.code_review.migrations import get_review
from workflows.code_review.paths import lane_memo_path, lane_state_path
from workflows.code_review.sessions import (
    expected_lane_branch,
    expected_lane_worktree,
    lane_acpx_session_name,
)


"""YoYoPod Core action execution helpers.

Each ``run_*`` function below is a pure, dependency-injected implementation of
one operator action (publish, push, merge, dispatch, tick). Callers inject
workspace-scoped primitives (``reconcile_fn``, ``_run``, ``audit``, etc.).
The live CLI (``python -m workflows``) and systemd-supervised runtime both
route through these functions, which are the single source of truth for the
action bodies.
"""


def run_publish_ready_pr(
    *,
    reconcile_fn: Callable[..., dict[str, Any]],
    run_fn: Callable[..., Any],
    audit_fn: Callable[..., Any],
    mark_pr_ready_for_review_fn: Callable[[Any], bool],
    repo_slug: str,
    repo_path: Path,
) -> dict[str, Any]:
    """Adapter-owned implementation of ``publish_ready_pr_raw``.

    All side-effectful primitives (reconcile, subprocess, audit, PR-ready) are
    injected so the adapter owns the decision flow without needing to reimport
    the wrapper's helpers.
    """
    status = reconcile_fn(fix_watchers=True)
    issue = status.get('activeLane')
    if not issue:
        return {'published': False, 'reason': 'no-active-lane'}
    impl = status.get('implementation') or {}
    worktree = Path(impl['worktree']) if impl.get('worktree') else None
    branch = impl.get('branch')
    if worktree is None or not branch:
        return {'published': False, 'reason': 'missing-worktree-or-branch'}
    if status.get('openPr'):
        pr = status.get('openPr') or {}
        if pr.get('isDraft') and mark_pr_ready_for_review_fn(pr.get('number')):
            after = reconcile_fn(fix_watchers=True)
            return {'published': True, 'prNumber': pr.get('number'), 'after': after}
        return {'published': False, 'reason': 'pr-already-exists', 'after': status}
    run_fn(['git', 'push', '-u', 'origin', branch], cwd=worktree)
    slug_title = re.sub(r'^\[[^\]]+\]\s*', '', issue.get('title') or '').strip()
    title = f"[codex] {slug_title}"
    body = f"Implements issue #{issue.get('number')}. Generated by wrapper-owned workflow watchdog."
    result = run_fn(
        ['gh', 'pr', 'create', '--repo', repo_slug, '--head', branch, '--title', title, '--body', body],
        cwd=repo_path,
    )
    after = reconcile_fn(fix_watchers=True)
    audit_fn(
        'publish-ready-pr',
        'Published ready-for-review PR for active lane',
        issueNumber=issue.get('number'),
        branch=branch,
    )
    stdout = getattr(result, 'stdout', '') or ''
    return {'published': True, 'result': stdout.strip(), 'after': after}


def run_push_pr_update(
    *,
    reconcile_fn: Callable[..., dict[str, Any]],
    run_fn: Callable[..., Any],
    audit_fn: Callable[..., Any],
) -> dict[str, Any]:
    """Adapter-owned implementation of ``push_pr_update_raw``."""
    status = reconcile_fn(fix_watchers=True)
    issue = status.get('activeLane')
    pr = status.get('openPr') or {}
    impl = status.get('implementation') or {}
    worktree = Path(impl['worktree']) if impl.get('worktree') else None
    branch = impl.get('branch') or pr.get('headRefName')
    local_head_sha = impl.get('localHeadSha')
    published_head_sha = pr.get('headRefOid')
    if not issue or not pr:
        return {'pushed': False, 'reason': 'missing-active-lane-or-pr', 'after': status}
    if worktree is None or not branch:
        return {'pushed': False, 'reason': 'missing-worktree-or-branch', 'after': status}
    if not local_head_sha or local_head_sha == published_head_sha:
        return {'pushed': False, 'reason': 'pr-already-current', 'after': status}
    run_fn(['git', 'push', 'origin', f'HEAD:{branch}'], cwd=worktree)
    after = reconcile_fn(fix_watchers=True)
    audit_fn(
        'push-pr-update',
        'Pushed updated repair head to existing PR branch',
        issueNumber=issue.get('number'),
        prNumber=pr.get('number'),
        branch=branch,
        headSha=local_head_sha,
    )
    return {'pushed': True, 'prNumber': pr.get('number'), 'headSha': local_head_sha, 'after': after}


def run_merge_and_promote(
    *,
    reconcile_fn: Callable[..., dict[str, Any]],
    run_fn: Callable[..., Any],
    audit_fn: Callable[..., Any],
    issue_remove_label_fn: Callable[[Any, str], Any],
    issue_close_fn: Callable[[Any, str], Any],
    issue_add_label_fn: Callable[[Any, str], Any],
    issue_comment_fn: Callable[[Any, str], Any],
    pick_next_lane_issue_fn: Callable[[], dict[str, Any] | None],
    now_iso_fn: Callable[[], str],
    active_lane_label: str,
    repo_slug: str,
    repo_path: Path,
) -> dict[str, Any]:
    """Adapter-owned implementation of ``merge_and_promote_raw``."""
    status = reconcile_fn(fix_watchers=True)
    issue = status.get('activeLane')
    pr = status.get('openPr') or {}
    if not issue or not pr:
        return {'merged': False, 'reason': 'missing-active-lane-or-pr'}
    run_fn(
        ['gh', 'pr', 'merge', str(pr.get('number')), '--repo', repo_slug, '--squash', '--delete-branch'],
        cwd=repo_path,
    )
    merged_at = now_iso_fn()
    issue_remove_label_fn(issue.get('number'), active_lane_label)
    close_comment = f"Merged in PR #{pr.get('number')} at {merged_at}. Closing the lane and moving workflow forward."
    issue_close_fn(issue.get('number'), close_comment)
    next_issue = pick_next_lane_issue_fn()
    if next_issue:
        issue_add_label_fn(next_issue.get('number'), active_lane_label)
        issue_comment_fn(
            next_issue.get('number'),
            f"Promoted to active lane after issue #{issue.get('number')} merged in PR #{pr.get('number')}.",
        )
    after = reconcile_fn(fix_watchers=True)
    audit_fn(
        'merge-and-promote',
        'Merged approved PR and promoted next lane',
        mergedPrNumber=pr.get('number'),
        closedIssueNumber=issue.get('number'),
        nextIssueNumber=(next_issue or {}).get('number'),
    )
    return {
        'merged': True,
        'mergedPrNumber': pr.get('number'),
        'closedIssueNumber': issue.get('number'),
        'nextIssueNumber': (next_issue or {}).get('number'),
        'after': after,
    }


def run_dispatch_lane_turn(
    *,
    status: dict[str, Any],
    forced_action: str | None,
    audit_action: str,
    now_iso_fn: Callable[[], str],
    close_acpx_session_fn: Callable[..., Any],
    ensure_acpx_session_fn: Callable[..., dict[str, Any]],
    show_acpx_session_fn: Callable[..., dict[str, Any] | None],
    run_prompt_fn: Callable[..., Any],
    prepare_lane_worktree_fn: Callable[..., dict[str, Any]],
    codex_model_for_issue_fn: Callable[..., str],
    get_issue_details_fn: Callable[[Any], dict[str, Any] | None],
    fallback_codex_model_for_prompt_error_fn: Callable[..., str | None],
    coder_agent_name_for_model_fn: Callable[[str | None], str],
    actor_labels_payload_fn: Callable[[str | None], dict[str, Any]],
    load_ledger_fn: Callable[[], dict[str, Any]],
    save_ledger_fn: Callable[[dict[str, Any]], Any],
    reconcile_fn: Callable[..., dict[str, Any]],
    audit_fn: Callable[..., Any],
    render_implementation_dispatch_prompt_fn: Callable[..., str],
    error_cls: type = subprocess.CalledProcessError,
) -> dict[str, Any]:
    """Adapter-owned implementation of ``_dispatch_lane_turn``.

    The function is the single place that turns a normalized status into either
    an actor-session dispatch or a well-known skip reason. Every side-effectful
    primitive is injected so the adapter owns the branching logic without
    bringing ACPX/GitHub/ledger-write concerns inline.
    """
    issue = status.get('activeLane')
    if not issue:
        return {'dispatched': False, 'reason': 'no-active-lane'}
    impl = status.get('implementation') or {}
    worktree = Path(impl['worktree']) if impl.get('worktree') else expected_lane_worktree(issue.get('number'))
    if worktree is None:
        return {'dispatched': False, 'reason': 'missing-worktree'}
    worktree.mkdir(parents=True, exist_ok=True)
    session_name = impl.get('sessionName') or lane_acpx_session_name(issue.get('number'))
    if not session_name:
        return {'dispatched': False, 'reason': 'missing-session-name'}
    branch = impl.get('branch') or expected_lane_branch(issue)
    if not branch:
        return {'dispatched': False, 'reason': 'missing-branch'}
    worktree_info = prepare_lane_worktree_fn(worktree=worktree, branch=branch, open_pr=status.get('openPr'))
    action = forced_action or ((impl.get('sessionActionRecommendation') or {}).get('action')) or 'restart-session'
    codex_model = impl.get('codexModel') or codex_model_for_issue_fn(
        issue,
        lane_state=impl.get('laneState'),
        workflow_state=(status.get('ledger') or {}).get('workflowState'),
        reviews=status.get('reviews') or {},
    )
    if action == 'no-action':
        return {'dispatched': False, 'reason': 'no-action'}
    if action == 'restart-session':
        close_acpx_session_fn(worktree=worktree, session_name=session_name)
    issue_details = get_issue_details_fn(issue.get('number'))
    ensured = ensure_acpx_session_fn(
        worktree=worktree,
        session_name=session_name,
        codex_model=codex_model,
        resume_session_id=impl.get('resumeSessionId'),
    )
    session_meta = show_acpx_session_fn(worktree=worktree, session_name=session_name) or {}
    attempt_at = now_iso_fn()
    attempt_id = f"{session_name}:{attempt_at}"
    prompt = render_implementation_dispatch_prompt_fn(
        issue=issue,
        issue_details=issue_details,
        worktree=worktree,
        lane_memo_path=Path(impl['laneMemoPath']) if impl.get('laneMemoPath') else lane_memo_path(worktree),
        lane_state_path=Path(impl['laneStatePath']) if impl.get('laneStatePath') else lane_state_path(worktree),
        open_pr=status.get('openPr'),
        action=action,
        workflow_state=(status.get('ledger') or {}).get('workflowState'),
    )
    session_record_id = session_meta.get('record_id') or ensured.get('acpxRecordId')
    try:
        prompt_result = run_prompt_fn(
            worktree=worktree,
            session_name=session_name,
            prompt=prompt,
            codex_model=codex_model,
        )
    except error_cls as exc:
        fallback_codex_model = fallback_codex_model_for_prompt_error_fn(
            acpx_record_id=session_record_id,
            codex_model=codex_model,
            exc=exc,
        )
        if not fallback_codex_model:
            raise
        codex_model = fallback_codex_model
        close_acpx_session_fn(worktree=worktree, session_name=session_name)
        ensured = ensure_acpx_session_fn(
            worktree=worktree,
            session_name=session_name,
            codex_model=codex_model,
            resume_session_id=None,
        )
        session_meta = show_acpx_session_fn(worktree=worktree, session_name=session_name) or session_meta
        session_record_id = session_meta.get('record_id') or ensured.get('acpxRecordId')
        prompt_result = run_prompt_fn(
            worktree=worktree,
            session_name=session_name,
            prompt=prompt,
            codex_model=codex_model,
        )
    ledger = load_ledger_fn()
    ledger.setdefault('implementation', {})
    ledger['codexModel'] = codex_model
    ledger['workflowActors'] = actor_labels_payload_fn(codex_model)
    ledger['implementation'] = {
        **ledger.get('implementation', {}),
        'session': session_meta.get('record_id') or ensured.get('acpxRecordId'),
        'previousSession': ledger.get('implementation', {}).get('previousSession'),
        'sessionRuntime': 'acpx-codex',
        'sessionName': session_name,
        'codexModel': codex_model,
        'agentName': coder_agent_name_for_model_fn(codex_model),
        'agentRole': 'coder_agent',
        'resumeSessionId': session_meta.get('session_id'),
        'worktree': str(worktree),
        'updatedAt': attempt_at,
        'branch': branch,
        'status': 'implementing' if not status.get('openPr') else ledger.get('workflowState'),
        'lastDispatchAttemptId': attempt_id,
        'lastDispatchAt': attempt_at,
        'lastRestartAttemptId': attempt_id if action == 'restart-session' else ledger.get('implementation', {}).get('lastRestartAttemptId'),
        'lastRestartAt': attempt_at if action == 'restart-session' else ledger.get('implementation', {}).get('lastRestartAt'),
    }
    save_ledger_fn(ledger)
    reconciled = reconcile_fn(fix_watchers=True)
    result = {
        'dispatched': True,
        'action': action,
        'issueNumber': issue.get('number'),
        'sessionRuntime': 'acpx-codex',
        'sessionName': session_name,
        'codexModel': codex_model,
        'sessionRecordId': session_meta.get('record_id') or ensured.get('acpxRecordId'),
        'resumeSessionId': session_meta.get('session_id'),
        'worktree': str(worktree),
        'worktreePrepared': worktree_info,
        'promptResult': prompt_result,
        'health': reconciled.get('health'),
    }
    audit_fn(
        audit_action,
        f"Dispatched persistent Codex lane turn via acpx session {session_name}",
        issueNumber=issue.get('number'),
        sessionName=session_name,
        sessionRecordId=result.get('sessionRecordId'),
        sessionAction=action,
    )
    return result


def run_dispatch_inter_review_agent_review(
    *,
    reconcile_fn: Callable[..., dict[str, Any]],
    load_ledger_fn: Callable[[], dict[str, Any]],
    save_ledger_fn: Callable[[dict[str, Any]], Any],
    audit_inter_review_agent_transition_fn: Callable[[dict[str, Any] | None, dict[str, Any] | None], Any],
    run_inter_review_agent_review_fn: Callable[..., dict[str, Any]],
    now_iso_fn: Callable[[], str],
    new_inter_review_agent_run_id_fn: Callable[[], str],
    actor_labels_payload_fn: Callable[[str | None], dict[str, Any]],
    inter_review_agent_model: str,
    internal_reviewer_agent_name: str,
    pending_summary: str = "Pending local unpublished branch review before publication.",
    agent_role: str = "internal_reviewer_agent",
) -> dict[str, Any]:
    """Adapter-owned implementation of ``dispatch_inter_review_agent_review_raw``.

    Drives the full review lifecycle:

      1. Reconcile + preflight guard.
      2. Mark the review as ``running`` in the ledger (via adapter helpers).
      3. Invoke the review CLI through ``run_inter_review_agent_review_fn``.
      4. Record success or failure, re-raise review errors to preserve the
         wrapper's historical contract with callers that rely on exception flow.
    """
    from workflows.code_review.reviews import (
        build_inter_review_agent_completed_review,
        build_inter_review_agent_failed_review,
        build_inter_review_agent_running_review,
    )

    status = reconcile_fn(fix_watchers=True)
    issue = status.get('activeLane')
    if not issue:
        return {'dispatched': False, 'reason': 'no-active-lane'}
    impl = status.get('implementation') or {}
    worktree = Path(impl['worktree']) if impl.get('worktree') else None
    if worktree is None:
        return {'dispatched': False, 'reason': 'missing-worktree'}
    preflight = ((status.get('preflight') or {}).get('interReviewAgent') or (status.get('preflight') or {}).get('claudeReview') or {})
    if not preflight.get('shouldRun'):
        return {'dispatched': False, 'reason': 'claude-preflight-blocked', 'preflight': preflight}
    head_sha = preflight.get('currentHeadSha')
    now_iso = now_iso_fn()
    run_id = new_inter_review_agent_run_id_fn()
    ledger = load_ledger_fn()
    ledger.setdefault('reviews', {})
    previous = get_review(ledger['reviews'], 'internalReview').copy()
    ledger['reviews']['internalReview'] = build_inter_review_agent_running_review(
        previous,
        run_id=run_id,
        head_sha=head_sha,
        now_iso=now_iso,
        model=inter_review_agent_model,
        pending_summary=pending_summary,
        agent_name=internal_reviewer_agent_name,
        agent_role=agent_role,
    )
    ledger['reviews'].pop('claudeCode', None)
    ledger['claudeModel'] = inter_review_agent_model
    ledger['interReviewAgentModel'] = inter_review_agent_model
    ledger['workflowActors'] = actor_labels_payload_fn(impl.get('codexModel'))
    save_ledger_fn(ledger)
    audit_inter_review_agent_transition_fn(previous, ledger['reviews']['internalReview'])
    memo_path = Path(impl['laneMemoPath']) if impl.get('laneMemoPath') else lane_memo_path(worktree)
    state_path = Path(impl['laneStatePath']) if impl.get('laneStatePath') else lane_state_path(worktree)
    try:
        result = run_inter_review_agent_review_fn(
            issue=issue,
            worktree=worktree,
            lane_memo_path=memo_path,
            lane_state_path=state_path,
            head_sha=head_sha,
        )
    except Exception as exc:
        failure_class = getattr(exc, 'failure_class', 'review_wrapper_failed')
        failure_summary = str(exc).strip() or 'Internal review agent failed without a detailed error message.'
        failed_at = now_iso_fn()
        ledger = load_ledger_fn()
        ledger.setdefault('reviews', {})
        previous = get_review(ledger['reviews'], 'internalReview').copy()
        ledger['reviews']['internalReview'] = build_inter_review_agent_failed_review(
            previous,
            run_id=run_id,
            head_sha=head_sha,
            requested_at=now_iso,
            failed_at=failed_at,
            failure_class=failure_class,
            failure_summary=failure_summary,
            model=inter_review_agent_model,
            pending_summary=pending_summary,
            agent_name=internal_reviewer_agent_name,
            agent_role=agent_role,
        )
        ledger['reviews'].pop('claudeCode', None)
        ledger['claudeModel'] = inter_review_agent_model
        ledger['interReviewAgentModel'] = inter_review_agent_model
        ledger['workflowActors'] = actor_labels_payload_fn(impl.get('codexModel'))
        save_ledger_fn(ledger)
        audit_inter_review_agent_transition_fn(previous, ledger['reviews']['internalReview'])
        raise
    completed_at = now_iso_fn()
    final_review = build_inter_review_agent_completed_review(
        result,
        run_id=run_id,
        head_sha=head_sha,
        started_at=now_iso,
        completed_at=completed_at,
        model=inter_review_agent_model,
        pending_summary=pending_summary,
        agent_name=internal_reviewer_agent_name,
        agent_role=agent_role,
    )
    ledger = load_ledger_fn()
    ledger.setdefault('reviews', {})
    previous = get_review(ledger['reviews'], 'internalReview').copy()
    ledger['reviews']['internalReview'] = final_review
    ledger['reviews'].pop('claudeCode', None)
    ledger['claudeModel'] = inter_review_agent_model
    ledger['interReviewAgentModel'] = inter_review_agent_model
    ledger['workflowActors'] = actor_labels_payload_fn(impl.get('codexModel'))
    save_ledger_fn(ledger)
    audit_inter_review_agent_transition_fn(previous, final_review)
    after = reconcile_fn(fix_watchers=True)
    return {
        'dispatched': True,
        'headSha': head_sha,
        'claudeModel': inter_review_agent_model,
        'interReviewAgentModel': inter_review_agent_model,
        'review': final_review,
        'after': after,
    }


def run_tick_raw(
    *,
    reconcile_fn: Callable[..., dict[str, Any]],
    audit_fn: Callable[..., Any],
    dispatch_inter_review_agent_review_fn: Callable[[], dict[str, Any]],
    dispatch_implementation_turn_fn: Callable[[], dict[str, Any]],
    publish_ready_pr_fn: Callable[[], dict[str, Any]],
    push_pr_update_fn: Callable[[], dict[str, Any]],
    merge_and_promote_fn: Callable[[], dict[str, Any]],
) -> dict[str, Any]:
    """Adapter-owned implementation of the wrapper's ``tick_raw``.

    Reads the pre-tick status via ``reconcile_fn`` (which writes health), then
    dispatches at most one forward action. Each dispatcher is injected so the
    adapter owns the routing logic without taking a dependency on the wrapper's
    entrypoints directly.
    """
    before = reconcile_fn(fix_watchers=True)
    action = before.get('nextAction') or {'type': 'noop', 'reason': 'no-forward-action-needed'}
    executed: dict[str, Any] | None = None
    action_type = action.get('type')
    if action_type == 'run_internal_review':
        executed = dispatch_inter_review_agent_review_fn()
    elif action_type == 'dispatch_codex_turn':
        executed = dispatch_implementation_turn_fn()
    elif action_type == 'publish_ready_pr':
        executed = publish_ready_pr_fn()
    elif action_type == 'push_pr_update':
        executed = push_pr_update_fn()
    elif action_type == 'merge_and_promote':
        executed = merge_and_promote_fn()
    if executed is None:
        after = reconcile_fn(fix_watchers=True)
    else:
        after = executed.get('after') or reconcile_fn(fix_watchers=True)
    audit_fn(
        'workflow-tick-action',
        f"Workflow tick chose action {action_type}",
        actionType=action_type,
        reason=action.get('reason'),
        issueNumber=action.get('issueNumber'),
        headSha=action.get('headSha'),
    )
    return {'before': before, 'action': action, 'executed': executed, 'after': after}
